#!/usr/bin/env ruby
oldrev, newrev = ARGV

def run(cmd)
  exit($?.exitstatus) unless system "umask 002 && #{cmd}"
end

run "bundle install"
run "rbenv rehash"

# clear cached assets (unversioned/ignored files)
run "git clean -x -f -- build/"

# clean unversioned files from vendor/plugins (e.g. old submodules)
run "git clean -d -f -- vendor/plugins"
